# version: '3.9'  # Use a recent Compose file version
# services:
#   postgres:
#     image: postgres:13
#     environment:
#       - POSTGRES_USER=airflow
#       - POSTGRES_PASSWORD=airflow
#       - POSTGRES_DB=airflow
#     ports:
#       - "5432:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U airflow"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   airflow-init:
#     image: apache/airflow:2.10.3
#     environment:
#       - AIRFLOW__CORE__LOAD_EXAMPLES=False
#       - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#       - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
#       - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
#     entrypoint: "bash -c 'airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com'"
#     depends_on:
#       postgres:
#         condition: service_healthy

#   airflow-webserver:
#     image: apache/airflow:2.10.3
#     environment:
#       - AIRFLOW__CORE__LOAD_EXAMPLES=False
#       - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#       - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
#       # change the below line to your host machine's IP address, username and password
#       # AIRFLOW__EXTRA__DB_CONN=postgresql+psycopg2://YOUR_USERNAME:YOUR_PASSWARD@host.docker.internal:5432/cms_staging_db
#       - AIRFLOW__EXTRA__DB_CONN=postgresql+psycopg2://postgres:asd456@host.docker.internal:5432/cms_staging_db
#       - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
#     ports:
#       - "8080:8080"
#     command: "airflow webserver"
#     depends_on:
#       postgres:
#         condition: service_healthy
#     volumes:
#     # change the below line to your local machine's path
#       - /Users/jamie/Documents/my_code/cms_health_data_pipeline/dags:/opt/airflow/dags
#       - /Users/jamie/Documents/my_code/cms_health_data_pipeline/logs:/opt/airflow/logs
#       - /Users/jamie/Documents/my_code/cms_health_data_pipeline/scripts:/opt/airflow/scripts 
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   airflow-scheduler:
#     image: apache/airflow:2.10.3
#     environment:
#       - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
#       # change the below line to your host machine's IP address, username and password
#       # AIRFLOW__EXTRA__DB_CONN=postgresql+psycopg2://YOUR_USERNAME:YOUR_PASSWARD@host.docker.internal:5432/cms_staging_db
#       - AIRFLOW__EXTRA__DB_CONN=postgresql+psycopg2://postgres:asd456@host.docker.internal:5432/cms_staging_db
#       - AIRFLOW__CORE__LOAD_EXAMPLES=False
#       - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#       - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOofyDDAmhZ37Si56s9PJVMBlAZJABtig=
#     command: "airflow scheduler"
#     depends_on:
#       airflow-webserver:
#         condition: service_healthy
#     volumes:
#       # change the below line to your local machine's path
#       - /Users/jamie/Documents/my_code/cms_health_data_pipeline/dags:/opt/airflow/dags
#       - /Users/jamie/Documents/my_code/cms_health_data_pipeline/logs:/opt/airflow/logs
#       - /Users/jamie/Documents/my_code/cms_health_data_pipeline/scripts:/opt/airflow/scripts
 
############################################################################################################

version: '3.9'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.10.3
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
    entrypoint: "bash -c 'airflow db init && airflow users create --username ${AIRFLOW_ADMIN_USER} --password ${AIRFLOW_ADMIN_PASSWORD} --firstname Admin --lastname Admin --role Admin --email ${AIRFLOW_ADMIN_EMAIL}'"
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    image: apache/airflow:2.10.3
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__EXTRA__DB_CONN=${EXTRA_DB_CONN}
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
    ports:
      - "8080:8080"
    command: "airflow webserver"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-scheduler:
    image: apache/airflow:2.10.3
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__EXTRA__DB_CONN=${EXTRA_DB_CONN}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
    command: "airflow scheduler"
    depends_on:
      airflow-webserver:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
